### ISSUE TITLE
timestamp issue 3d ouster points

### ISSUE THREAD

**Issue by PetropoulakisPanagiotis** [PRBonn/kinematic-icp#34]
This is the ouster message: 

```
header:
  stamp:
    sec: 637
    nanosec: 296000000
  frame_id: os_sensor
height: 32
width: 1024
fields:
- name: x
  offset: 0
  datatype: 7
  count: 1
- name: y
  offset: 4
  datatype: 7
  count: 1
- name: z
  offset: 8
  datatype: 7
  count: 1
- name: intensity
  offset: 16
  datatype: 7
  count: 1
- name: ring
  offset: 24
  datatype: 4
  count: 1
is_bigendian: false
point_step: 32
row_step: 32768
data:
- 0
- 0
- 128
- 127

```

I get:     RCLCPP_WARN_ONCE(rclcpp::get_logger("kinematic_icp_ros"),
                     "Field 't', 'timestamp', 'time', or 'stamps'  does not exist. "
                     "Disabling scan deskewing"); in my terminal

Any fix?
